# Generated by Django 4.0.2 on 2022-02-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedatamanager',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeedatamanager',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeedatamanager',
            name='employee_start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
