# Generated by Django 4.0.2 on 2022-03-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_managerdata_alter_employeedatamanager_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedatamanager',
            name='isManager',
            field=models.BooleanField(default=False),
        ),
    ]
