# Generated by Django 4.0.2 on 2022-03-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_employeedatamanager_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedatamanager',
            name='manager_id',
            field=models.ForeignKey(blank=True, default='-', on_delete=django.db.models.deletion.CASCADE, to='baseapp.managerdata'),
        ),
    ]
